### ISSUE TITLE
ERROR: Jest worker encountered 3 child process exceptions

### ISSUE THREAD

**Issue by akshayvijayjain** [rkoziol/react-typescript-jest-boilerplate#57]
exceeding retry limit STACK: Error: Jest worker encountered 3 child process exceptions, exceeding retry limit.

When running npm run test:jest:coverage
@rkoziol 
![image](https://github.com/rkoziol/react-typescript-jest-boilerplate/assets/166013155/2069bee6-cfb0-498d-8a76-ead929dd56c1)

**Comment by rkoziol** [comment]
Thank you for letting me know about this issue @akshayvijayjain It means a lot to me because... it's my first issue created for this package, super excited! :D

Anyway - I fixed the problem with the new release, please check and let me know :)
